---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uclubperu/public_html/prueba-git/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH/index.php
    - /bin/cp test.txt $DEPLOYPATH/test.txt
