deployment:
  tasks:
    - export DEPLOYPATH=/home/uclubperu/public_html/prueba-git/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --exclude='.git' --exclude='.github' --exclude='.idea' --exclude='.cpanel.yml' ./ $DEPLOYPATH
